SanjayDevTech/Code-with-love

cpp/Ojas032_Merge_Sort.cpp

@SanjayDevTech please check the PR

Added Merge sort

---

cpp/suryakamalog_CountingSort.cpp

Counting sort is a sorting technique based on keys between a specific range. It works by counting the number of objects having distinct key values (kind of hashing). Then doing some arithmetic to calculate the position of each object in the output sequence.

Added suryakamalog_CountingSort.cpp

---

cpp/hritikkhurana10sm_InsertionSort.cpp

Created hritikkhurana_InsertionSort.cpp
*sorting using insertion sort

Created hritikkhurana_InsertionSort.cpp

---

CONTRIBUTORS.md
kotlin/Giancarmine_HelloWorld.kts
kotlin/elgiancar_HelloWorld.kts

Thank you for the opportunity!

Add kotlin helloworld

---

cpp/DhruvSinghal_HeapSort.cpp

- heapsort added
- Most efficient sorting algorithm

Adds HeapSort

---

cpp/suryakamalog_PascalTrianglePattern.cpp

Pascal’s triangle is a triangular array of the binomial coefficients. Write a function that takes an integer value n as input and prints first n lines of the Pascal’s triangle.
Eg. if n = 6 then pattern would be
1  
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1

Added suryakamalog_PascalTrianglePattern.cpp

---

cpp/suryakamalog_FlyodTrianglePattern.cpp
cpp/suryakamalog_PascalTrianglePattern.cpp

Floyd's triangle is a right-angled triangular array of natural numbers, used in computer science education. It is named after Robert Floyd. It is defined by filling the rows of the triangle with consecutive numbers, starting with a 1 in the top left corner. 
Given n, print Flyod's Triangle upto n rows.
eg. n = 5
Output will be
1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15

Added suryakamalog_FlyodTrianglePattern.cpp

---

CONTRIBUTORS.md
php/sam0hack_bubbleSort.php
php/sam0hack_quickSort.php
php/sam0hack_radixSort.php
php/sam0hack_selectionSort.php

1. Bubble Sort
2. Quick Sort
3. Radix Sort
4. Selection Sort
#4

Added: Sorting algorithms

---

cpp/SangeetaMishra_leapyear.cpp

This program tells whether the given year is leap year or not

Leap year or not program in C++

---

CONTRIBUTORS.md
kotlin/aaishikasb_ascii.kt
kotlin/aaishikasb_leapyear.kt
kotlin/aaishikasb_swap.kt

[x] ASCII Program in Kotlin
[x] Swap Numbers Program in Kotlin
[x] Leap Year Program in Kotlin
[x] Added name to CONTRIBUTORS.md

Added Programs in Kotlin

---

python/kishanpython_prime_number_algo.py

Algo to check and print the prime number

Prime Number

---

cpp/sejalshri_palindrome.cpp
cpp/sejalshri_primenumbercheck.cpp

@SanjayDevTech kindly review this PR.

in reference to #1

---

cpp/Shashwat_Mishra_DFS.cpp

Please review and accept my PR.
I have added a CPP file for depth first search in graphs.
I have also added the comments for better understanding.

add depth first search file

---

cpp/ganeshbhandarkar_GRAPH_DFS_BFS.cpp

Added Graph DFS BFS Code in CPP

Graph DFS BFS code added in cpp

---

python/Hariom1509_leapyear.py

Created a python script to find out if a year is a leap year or not  based on issue #46

Created leapyear.py

---

python/mansuuk_leapyear.py

Added the leapyear py code, please approve @SanjayDevTech

added leapyear py --hacktoberfest

---

cpp/Aditya-Shrivastava_TarjansAlgorithm.cpp

Implemented Tranjans algorithms to find:
Bridges in a graph
Articulation Points in a graph
Strongly Connected Components in a graph

Added Tarjans algorithm under cpp

---

cpp/shivikasaggar_CamelCasePattern.cpp
cpp/shivikasaggar_CheckAnagramOrNot.cpp
cpp/shivikasaggar_QuickSort.cpp

Code for camel case pattern in c++.
Please merge it.

Camel case Pattern code

---

cpp/shivikasaggar_CamelCasePattern.cpp
cpp/shivikasaggar_CheckAnagramOrNot.cpp
cpp/shivikasaggar_QuickSort.cpp
cpp/shivikasaggar_UglyNumbersUsingDP.cpp

Added code for finding nth ugly number in c.
Please merge this pull request.

code for finding nth ugly number.

---

python/mansuuk_radixSort.py

added radix sort in python

---

CONTRIBUTORS.md
js/sahil9001_fibbonaci.js

algo: Added fibbonaci sequence algorithm

---

CONTRIBUTORS.md
cpp/Diagonal_diff.cpp

This was a simple hackerank problem

added diagonal differnece of matrix

---

python/sethiojas_MergeSort.py

merge sort in python

---

python/mansuuk_generatePrime.py

Generates prime numbers upto a limit using a highly efficient algorithm, Sieve of Eratosthenes.

added prime number generator python code

---

cpp/Zeeshan-2k1_InterpolationSearch.cpp

Issue #4 Added Interpolation Search Algortihm in cpp. Please reveiw it and merge it. Thank You.

Added Interpolation Search in cpp

---

python/codingCapricorn_ShellSort.py

Added Shell Sort in Python

---

cpp/ayush523_leapyear.cpp

added program for leap year

---

cpp/promaroy_leapyear.cpp

added cpp code for leap year in cpp folder

added cpp code for leap year

---

c/promaroy_BubbleSort.c

added bubble sort code in C

---

Binary Search/saiharsha-22_inorder_program.java

Written a Java code for Binary search tree for inorder traversal using stack operation.

added a inorder program for binary tree in java using stack

---

cpp/hritikchaudhary_SieveofEratosthenes.cpp

The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million. http://en.wikipedia.org/wiki/Sieve_of_Eratosthenes

Added Sieve of Eratosthenes Algorithm for Prime Numbers

---

python/mansuuk_diamondPatternCentre.py

added diamond pattern printing python code

---

.github/workflows/greet-contributors.yml

Issue no. #80 
This action greet all the wonderful contributors within a Pull Request. :tada: 
Github Action Link : [greet-contributors-action](https://github.com/marketplace/actions/greet-contributors-action)

Integrated greet-contributors action

---

html/Kshitij9896_HelloWorld.html
python/kshitij9896_BinarySearchAlgoritham.py
python/kshitij9896_LinearSearchAlgoritham.py

Binary & Linear Serach in Python Added

---

js/vistheu_returning_largest_number.js

P.S. i'm sorry if i make a mistake on the code, commit or the request pull, because this is my first time contributing to an open source

Returning the Largest Number in an array on JS

---

CONTRIBUTORS.md
js/sejalshri_pancakesort.js

@SanjayDevTech  I have added pancake sorting algorithm in Javascript . kindly review it.

sejalshri_pancakesort.js  #47

---

cpp/pranav230_DFS.cpp

I have added the file for DFS using adjacency Matrix named pranav230_DFS.cpp in the cpp folder. One that is present in cpp folder is using adjacency list.

Added DFS in cpp

---

js/karn21_insertionSort.js

Added javascript implementation of insertion sort.

add js insertionSort

---

cpp/southpole01_butterfly.cpp
cpp/southpole01_prime.cpp

Commit 1: This code print a butterfly of variable size.(ISSUE #5 )
Commit 2: Print prime upto integer n. (ISSUE #1)

Added a Butterfly pattern (#5) and Prime using Seive(#1)

---

python/Mohit_convolution_python.py

This program performs a convolution operation on an image. Given the absolute path to an image (png) and a filter(box, gaussian, edge, sharpen) as input the algorithm applies the filter on the image and displays the output image. Coded in python with easy and self-explanatory comments.

Convolution Operation in Python

---

java/Aayushee25_SinglyLL.java

Added java program for creating and displaying singly linked list.

Created Aayushee25_SinglyLL.java

---

star_pattern.c

Mirror image of a right angled triangle pattern in C. Issue #583

Add Star pattern

---

c/lsb4_bubbleSort.c

The user can choose the size and the elements of the array and the ordering style.

BubbleSort C

---

cpp/lsb4_bubbleSort.cpp

The user can choose the size and the elements of the array and the ordering style.

BubbleSort C++

---

c/lumendesp_BubbleSort.c

Bubble Sort in C language with:
- Array size option;
- Array elements option;
- Ordering option.

Bubble Sort in C

---

cpp/lumendesp_BubbleSort.cpp

Bubble Sort with:
- Array size option;
- Array elements option;
- Ordering option.

Bubble Sort in C++

---

python/rohan300557_leapyear.py

rohan300557_leapyear.py contains code to find out if the year is a leap year or not. I used the Function method.

Added rohan300557_leapyear.py

---

Linear Search/anukaal_linearsearch.py

created linear_search

---

js/ayush_es6.js

added sample for arrow function, default parameter, let keyword, etc

sample es6 code added in js folder

---

python/alvinma_RecursiveInsertionSort.py

Adding a insertion sort algorithm implementation done in a recursive method than the usual iterative methods.

Recursive Insertion Sort Implementation in Python

---

python/alvinma_RecursiveBubbleSort.py

Adding a bubble sort algorithm implementation done in a recursive method than the usual iterative methods.

Recursive Bubble Sort Implementation in Python

---

cpp/alvinma_RecursiveInsertionSort.cpp

Adding a insertion sort algorithm implementation done in a recursive method than the usual iterative methods.

Recursive Insertion Sort Implementation in C++

---

cpp/alvinma_RecursiveBubbleSort.cpp

Adding a bubble sort algorithm implementation done in a recursive method the the usual iterative methods.

Recursive Bubble Sort Implementation in C++

---

cpp/sanyamSelectionSort.cpp

added a cpp code for selection sort

Add code for Selection Sort

---

cpp/pranav230_Kadane_Algorithm.cpp

Added the Kadane Algorithm file named as pranav230_Kadane_Algorithm.cpp in the cpp folder.

Added Kadane Algorithm

---

php/bhubhanshu_leapyear.php

#46  Added Php code to check if year is a leap year or not

Added Leap Year Code in Php

---

js/imsubhra_InsertionSort.js

Added insertion sort algorithm

---

c/keerti_BST.c

Added c program keerti_BST.c in folder named c

Added keerti_BST.c

---

c/AmanSahu_leap_year_or_not.c

I have Added program for checking leap year

Added program for checking leap year

---

c/jainaayush01_CircularQueue.c
c/jainaayush01_Circular_LL.c
c/jainaayush01_Doubly_LL.c
c/jainaayush01_LinkedList.c
c/jainaayush01_Queue_using_LL.c
c/jainaayush01_SimpleQueue.c
c/jainaayush01_Stack_using_LL.c
c/jainaayush_Stack_Implementaion.c

I have added various data structures implementations in C language
Stack, Queue using both array and Linked List
Circular Queue
Simple Circular and Doubly Linked List

Added Data Structures Implementation in C

---

cpp/Shinigami-Daikou_FibonacciHuge.cpp
cpp/Shinigami-Daikou_Fibonacci_SumLastDigit.cpp
cpp/Shinigami-Daikou_Fibonacci_SumSquares.cpp
cpp/Shinigami-Daikou_NthFibonacci.cpp
cpp/Shinigami-Daikou_Nthfibonacci_last_digit.cpp
cpp/Shinigami-Daikou_PisanoPeriod.cpp

I've added some basic programs of fibonacci numbers in C++.

Added Basic Programs On Fibonacci

---

cpp/FinalGetsugaa_KadanesAlgo.cpp
cpp/FinalGetsugaa_leapyear.cpp

Added Kadanes Algorithm Implementation in C++ and Program to check whether year is leap or not. [ Issue #46 ]

Kadanes Algorithm Implementation and Leapyear Program (in C++)
